# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a509264abf09519488e41a351f47c78badc7768317999b27467f4dee97a44120b586d05b1834004d9501cababcc8b7f58e7d3ce5334ecb1ee6011b59d238dcf

test:
  secret_key_base: 9cc6164077ce4b483ae22d83e3b135c6c78eee0b7dd3f2963b6353c7b919e394f5447d337442dabd011a358a2eba1631919ea170dd033b438bfb367d70ab4001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
